<?php
/**
 * Contact and inquiry helpers.
 *
 * @package Langit
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Render a configured contact form shortcode with a graceful placeholder.
 */
function langit_contact_form_area() {
	$shortcode          = trim( langit_theme_mod( 'contact_form_shortcode' ) );
	$rendered_shortcode = '';
	$shortcode_ready    = false;

	if ( ! empty( $shortcode ) ) {
		$rendered_shortcode = do_shortcode( $shortcode );
		$shortcode_ready    = ! empty( trim( $rendered_shortcode ) ) && trim( $rendered_shortcode ) !== $shortcode;
	}
	?>
	<div class="form-placeholder contact-form-panel">
		<?php if ( ! empty( $shortcode ) && $shortcode_ready ) : ?>
			<div class="contact-form-panel__shortcode fluentform">
				<?php
				// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Shortcode output is generated by trusted WordPress form plugins.
				echo $rendered_shortcode;
				?>
			</div>
		<?php else : ?>
			<form class="form-placeholder__fields contact-fallback-form" method="post" action="<?php echo esc_url( 'mailto:' . sanitize_email( langit_theme_mod( 'contact_email_address' ) ) ); ?>" enctype="text/plain">
				<label>
					<span><?php esc_html_e( 'Nama', 'langit' ); ?></span>
					<input type="text" name="Nama" autocomplete="name" required>
				</label>
				<label>
					<span><?php esc_html_e( 'Perusahaan', 'langit' ); ?></span>
					<input type="text" name="Perusahaan" autocomplete="organization">
				</label>
				<label>
					<span><?php esc_html_e( 'Email', 'langit' ); ?></span>
					<input type="email" name="Email" autocomplete="email" required>
				</label>
				<label>
					<span><?php esc_html_e( 'Nomor Telepon', 'langit' ); ?></span>
					<input type="tel" name="Nomor Telepon" autocomplete="tel">
				</label>
				<label>
					<span><?php esc_html_e( 'Jenis Kebutuhan', 'langit' ); ?></span>
					<select name="Jenis Kebutuhan">
						<option value=""><?php esc_html_e( 'Pilih kebutuhan', 'langit' ); ?></option>
						<option value="cctv"><?php esc_html_e( 'CCTV & Security System', 'langit' ); ?></option>
						<option value="networking"><?php esc_html_e( 'Networking Infrastructure', 'langit' ); ?></option>
						<option value="mechanical-electrical"><?php esc_html_e( 'Mechanical Electrical', 'langit' ); ?></option>
						<option value="fire-alarm"><?php esc_html_e( 'Fire Alarm System', 'langit' ); ?></option>
						<option value="audio-public-address"><?php esc_html_e( 'Audio & Public Address', 'langit' ); ?></option>
						<option value="maintenance"><?php esc_html_e( 'Installation & Maintenance', 'langit' ); ?></option>
					</select>
				</label>
				<label class="form-placeholder__message">
					<span><?php esc_html_e( 'Pesan', 'langit' ); ?></span>
					<textarea name="Pesan" rows="8" required></textarea>
				</label>
				<button type="submit"><?php esc_html_e( 'Send Inquiry', 'langit' ); ?></button>
			</form>
			<div class="shortcode-placeholder">
				<?php esc_html_e( 'Add or activate a form shortcode in Appearance > Customize.', 'langit' ); ?>
			</div>
		<?php endif; ?>
	</div>
	<?php
}

/**
 * Render a reusable WhatsApp quick contact card.
 */
function langit_whatsapp_quick_contact() {
	?>
	<aside class="quick-contact-card">
		<p class="section-eyebrow"><?php echo esc_html( langit_theme_mod( 'contact_quick_eyebrow' ) ); ?></p>
		<h3><?php echo esc_html( langit_theme_mod( 'contact_quick_title' ) ); ?></h3>
		<p><?php echo esc_html( langit_theme_mod( 'contact_quick_description' ) ); ?></p>
		<?php
		langit_button(
			array(
				'url'   => langit_contact_whatsapp_url(),
				'label' => langit_theme_mod( 'contact_quick_button_text' ),
			)
		);
		?>
	</aside>
	<?php
}
