<?php
/**
 * Contact and inquiry helpers.
 *
 * @package Langit
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Render a configured contact form shortcode with a graceful placeholder.
 */
function langit_contact_form_area() {
	$shortcode          = trim( langit_theme_mod( 'contact_form_shortcode' ) );
	$rendered_shortcode = '';
	$shortcode_ready    = false;

	if ( ! empty( $shortcode ) ) {
		$rendered_shortcode = do_shortcode( $shortcode );
		$shortcode_ready    = ! empty( trim( $rendered_shortcode ) ) && trim( $rendered_shortcode ) !== $shortcode;
	}
	?>
	<div class="form-placeholder contact-form-panel">
		<?php if ( ! empty( $shortcode ) && $shortcode_ready ) : ?>
			<div class="contact-form-panel__shortcode fluentform">
				<?php
				// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Shortcode output is generated by trusted WordPress form plugins.
				echo $rendered_shortcode;
				?>
			</div>
		<?php else : ?>
			<div class="form-placeholder__fields" aria-hidden="true">
				<span><?php esc_html_e( 'Nama', 'langit' ); ?></span>
				<span><?php esc_html_e( 'Perusahaan', 'langit' ); ?></span>
				<span><?php esc_html_e( 'Email', 'langit' ); ?></span>
				<span><?php esc_html_e( 'Nomor Telepon', 'langit' ); ?></span>
				<span><?php esc_html_e( 'Jenis Kebutuhan', 'langit' ); ?></span>
				<span class="form-placeholder__message"><?php esc_html_e( 'Pesan', 'langit' ); ?></span>
			</div>
			<div class="shortcode-placeholder">
				<?php esc_html_e( 'Add or activate a form shortcode in Appearance > Customize.', 'langit' ); ?>
			</div>
		<?php endif; ?>
	</div>
	<?php
}

/**
 * Render a reusable WhatsApp quick contact card.
 */
function langit_whatsapp_quick_contact() {
	?>
	<aside class="quick-contact-card">
		<p class="section-eyebrow"><?php echo esc_html( langit_theme_mod( 'contact_quick_eyebrow' ) ); ?></p>
		<h3><?php echo esc_html( langit_theme_mod( 'contact_quick_title' ) ); ?></h3>
		<p><?php echo esc_html( langit_theme_mod( 'contact_quick_description' ) ); ?></p>
		<?php
		langit_button(
			array(
				'url'   => langit_contact_whatsapp_url(),
				'label' => langit_theme_mod( 'contact_quick_button_text' ),
			)
		);
		?>
	</aside>
	<?php
}
